export const CRITICAL_DATA_FETCH_ERROR = "CRITICAL_DATA_FETCH_ERROR";
export const NO_ACCESS_ERROR = "NO_ACCESS_ERROR";
export const UNAVAILABLE_IN_CURRENT_LOCATION_STATUS =
  "UNAVAILABLE_IN_CURRENT_LOCATION_STATUS";
