export const Errors = {
  CRITICAL_DATA_FETCH_ERROR: 'CRITICAL_DATA_FETCH_ERROR',
  NO_ACCESS_ERROR: 'NO_ACCESS_ERROR',
  UNAVAILABLE_IN_CURRENT_LOCATION_STATUS: 'UNAVAILABLE_IN_CURRENT_LOCATION_STATUS',
  401: 401,
} as const;
