/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/service/{service_name}/version": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        service_name: string;
      };
      cookie?: never;
    };
    /** Get available versions to install */
    get: operations["getVersions"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/service/{service_name}/install": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get installed version */
    get: operations["getInstalledVersion"];
    put?: never;
    /** Install service */
    post: operations["installService"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/service/{service_name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Explore installed service version details */
    get: operations["describeService"];
    put?: never;
    post?: never;
    /** Delete service */
    delete: operations["deleteService"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/service/{service_name}/update": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get update vesion */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          service_name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": unknown[];
          };
        };
      };
    };
    /** Update version from update overview */
    put: {
      parameters: {
        query: {
          version: string;
        };
        header?: never;
        path: {
          service_name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/service/{service_name}/release": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get release version */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          service_name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": unknown[];
          };
        };
      };
    };
    /** Upgrade version from release overview */
    put: {
      parameters: {
        query: {
          version: string;
        };
        header?: never;
        path: {
          service_name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/service/{service_name}/downgrade": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all installed versions for downgrade */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          service_name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": {
              /** @example 200 */
              code?: number;
              /** @example [
               *       "2.0.2",
               *       "2.0.1"
               *     ] */
              data?: unknown[];
            };
          };
        };
      };
    };
    /** Downgrade version from version overview */
    put: {
      parameters: {
        query: {
          version: string;
        };
        header?: never;
        path: {
          service_name: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/services/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get services statuses */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": unknown[];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: {
    /** @description Access token is missing or invalid */
    UnauthorizedError: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
    /** @description Account access is denied */
    AccountAccessError: {
      headers: {
        [name: string]: unknown;
      };
      content?: never;
    };
  };
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getVersions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        service_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown[];
        };
      };
    };
  };
  getInstalledVersion: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        service_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example 200 */
            code?: number;
            /** @example 1.1.1 */
            data?: string;
          };
        };
      };
    };
  };
  installService: {
    parameters: {
      query: {
        version: string;
      };
      header?: never;
      path: {
        service_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  describeService: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        service_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Success */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example 1.1.1 */
            version?: string;
            /** @example latest */
            tag?: string;
            /** @example 2024-02-09 */
            date?: string;
            required?: {
              /** @example 1.0.0 */
              admin?: string;
              /** @example 1.0.0 */
              compute?: string;
            };
            /** @example [
             *       {
             *         "name": "apigw",
             *         "tag": "1.0.0",
             *         "description": {
             *           "warnings": "* warning1\r\n* warning2",
             *           "features": "* feature1\r\n* feature2",
             *           "security_fixes": "* security1\r\n* security2",
             *           "bug_fixes": "* bug1\r\n* bug2",
             *           "depricated": "* depricated1\r\n* depricated2",
             *           "known_issues": ""
             *         }
             *       },
             *       {
             *         "name": "engine",
             *         "tag": "1.0.0",
             *         "ui_url": "/billing/engine/remoteEntry.js",
             *         "description": {
             *           "warnings": "* warning1\r\n* warning2",
             *           "features": "* feature1\r\n* feature2",
             *           "security_fixes": "* security1\r\n* security2",
             *           "bug_fixes": "* bug1\r\n* bug2",
             *           "depricated": "* depricated1\r\n* depricated2",
             *           "known_issues": ""
             *         }
             *       }
             *     ] */
            applications?: unknown[];
          };
        };
      };
    };
  };
  deleteService: {
    parameters: {
      query?: {
        /** @description Default value is empty (false) */
        delete_persistent_data?: string;
        /** @description Default value is empty (false) */
        delete_backup_data?: string;
      };
      header?: never;
      path: {
        service_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No content */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
